-- ============================================================
-- GUAYABO · Semillas iniciales (config, catálogos y consecutivos)
-- Ejecutar después de schema.sql, sobre una base recién creada.
-- Los datos reales (clientes, prendas, pedidos, pagos) se cargan con
-- el script de migración importar.ts desde el export de Google Sheets.
-- ============================================================

-- -------- Configuración (marca, visual, reglas de negocio) --------
insert into public.config (clave, valor, tipo, grupo, descripcion, activo) values
('NOMBRE_MARCA','GUAYABO','texto','MARCA','Nombre de la marca', true),
('LEMA','Tener guayabo nunca había sido tan bacanooo','texto','MARCA','Frase de la marca', true),
('LOGO_URL','','texto','MARCA','URL del logo (si está vacío se usa el logo incluido)', true),
('TELEFONO','','texto','MARCA','Teléfono de contacto', true),
('WHATSAPP','','texto','MARCA','WhatsApp (solo números, con indicativo)', true),
('EMAIL','','texto','MARCA','Correo de contacto', true),
('INSTAGRAM','@guayabo','texto','MARCA','Instagram', true),
('DIRECCION','','texto','MARCA','Dirección', true),
('CIUDAD','Bogotá','texto','MARCA','Ciudad', true),
('INFO_ADICIONAL','','texto','MARCA','Texto libre para comprobantes', true),
('MONEDA','$','texto','MARCA','Símbolo de moneda', true),
('COLOR_PRIMARIO','#D2DE52','color','VISUAL','Color principal (verde GUAYABO)', true),
('COLOR_SECUNDARIO','#E8288E','color','VISUAL','Color secundario (rosa GUAYABO)', true),
('COLOR_BOTON','#E8288E','color','VISUAL','Color de los botones principales', true),
('COLOR_FONDO','#FFFDF4','color','VISUAL','Fondo de la aplicación', true),
('COLOR_TARJETA','#FFFFFF','color','VISUAL','Fondo de las tarjetas', true),
('COLOR_TEXTO','#191914','color','VISUAL','Color del texto', true),
('MODO','claro','lista:claro,oscuro','VISUAL','Modo claro u oscuro', true),
('RADIO_BORDE','22','numero','VISUAL','Redondeo de las tarjetas (px)', true),
('TIEMPO_ENTREGA','15','numero','PEDIDOS','Días estimados de entrega', true),
('DIAS_ENTREGA_PROXIMA','3','numero','PEDIDOS','Días antes de la entrega para avisar', true),
('PERMITIR_CANCELAR','TRUE','booleano','PEDIDOS','Permitir cancelar pedidos', true),
('PERMITIR_EDITAR_FECHA','TRUE','booleano','PEDIDOS','Permitir cambiar la fecha de entrega', true),
('VENTA_BAJO_PEDIDO','FALSE','booleano','PEDIDOS','Vender aunque no haya stock', true),
('ESTADO_INICIAL_PEDIDO','Pedido recibido','texto','PEDIDOS','Estado con el que nace un pedido', true),
('ESTADO_INICIAL_VENTA','Entregado','texto','PEDIDOS','Estado con el que nace una venta directa', true),
('STOCK_MINIMO','5','numero','INVENTARIO','Stock mínimo por defecto', true),
('ALERTAS_STOCK','TRUE','booleano','INVENTARIO','Mostrar alertas de stock bajo', true),
('PERMITIR_STOCK_NEGATIVO','FALSE','booleano','INVENTARIO','Permitir stock negativo', true),
('MOSTRAR_AGOTADOS','TRUE','booleano','INVENTARIO','Mostrar prendas agotadas en el catálogo', true),
('DESCONTAR_STOCK_APARTADO','TRUE','booleano','INVENTARIO','Descontar stock al crear un apartado', true),
('DIAS_APARTADO','15','numero','APARTADOS','Días de vigencia de un apartado', true),
('DIAS_AVISO_APARTADO','3','numero','APARTADOS','Días antes del vencimiento para avisar', true),
('ABONO_MINIMO_PORCENTAJE','30','numero','APARTADOS','Abono mínimo sugerido (%)', true),
('UTILIDAD_BRUTA_INCLUYE_DESCUENTO','TRUE','booleano','FINANZAS','Restar el descuento de la utilidad bruta', true),
('UTILIDAD_NETA_INCLUYE_GASTOS','TRUE','booleano','FINANZAS','Restar los gastos en la utilidad neta', true),
('ENVIO_SUMA_VENTA','FALSE','booleano','FINANZAS','El envío cobrado cuenta como venta', true),
('ENVIO_ES_GASTO','TRUE','booleano','FINANZAS','El envío se considera costo del pedido', true),
('COMISION_PORCENTAJE','0','numero','FINANZAS','Comisión aplicada sobre cada venta (%)', true),
('SOLO_PEDIDOS_PAGADOS','FALSE','booleano','FINANZAS','Contar solo pedidos pagados en las ventas', true),
('DASH_PERIODO','mes','lista:hoy,semana,mes,30dias','DASHBOARD','Período predeterminado', true),
('DASH_TARJETAS','ventas_hoy,ventas_mes,recibido,pendiente,pedidos_pendientes,pedidos_entregados,apartados_activos,total_prendas,stock_bajo,costo_mercancia,gastos,utilidad_bruta,utilidad_neta','texto','DASHBOARD','Tarjetas visibles (separadas por coma)', true),
('VERSION','1.0.0','texto','SISTEMA','Versión instalada', true)
on conflict (clave) do nothing;

-- -------- Consecutivos (siguiente = último usado + 1 en la hoja) --------
insert into public.consecutivos (entidad, prefijo, digitos, siguiente) values
('PEDIDO','GUAYABO',4,31),
('CLIENTE','CLI',4,13),
('PRENDA','GY',4,11),
('PAGO','PAG',4,35),
('APARTADO','APT',4,6),
('GASTO','GAS',4,19)
on conflict (entidad) do nothing;

-- -------- Catálogos (listas) --------
insert into public.listas (tipo, nombre, hex, ambito, es_final, orden, activo) values
('CATEGORIA','Camisetas',null,null,false,1,true),
('CATEGORIA','Hoodies',null,null,false,2,true),
('CATEGORIA','Pantalones',null,null,false,3,true),
('CATEGORIA','Gorras',null,null,false,4,true),
('CATEGORIA','Chaquetas',null,null,false,5,true),
('CATEGORIA','Accesorios',null,null,false,6,true),
('CATEGORIA','Otros',null,null,false,7,true),
('TALLA','XS',null,null,false,1,true),
('TALLA','S',null,null,false,2,true),
('TALLA','M',null,null,false,3,true),
('TALLA','L',null,null,false,4,true),
('TALLA','XL',null,null,false,5,true),
('TALLA','XXL',null,null,false,6,true),
('TALLA','Única',null,null,false,7,true),
('COLOR','Negro','#111111',null,false,1,true),
('COLOR','Blanco','#FFFFFF',null,false,2,true),
('COLOR','Azul oscuro','#22307A',null,false,3,true),
('COLOR','Verde GUAYABO','#D2DE52',null,false,4,true),
('COLOR','Rosa GUAYABO','#E8288E',null,false,5,true),
('COLOR','Beige','#E8DCC8',null,false,6,true),
('COLOR','Rojo','#D33A2C',null,false,7,true),
('COLOR','Gris','#8A8A8A',null,false,8,true),
('METODO_PAGO','Efectivo',null,null,false,1,true),
('METODO_PAGO','Transferencia',null,null,false,2,true),
('METODO_PAGO','Nequi',null,null,false,3,true),
('METODO_PAGO','Daviplata',null,null,false,4,true),
('METODO_PAGO','Bancolombia',null,null,false,5,true),
('METODO_PAGO','Tarjeta',null,null,false,6,true),
('METODO_PAGO','Otro',null,null,false,7,true),
('CATEGORIA_GASTO','Mercancía',null,null,false,1,true),
('CATEGORIA_GASTO','Producción',null,null,false,2,true),
('CATEGORIA_GASTO','Transporte',null,null,false,3,true),
('CATEGORIA_GASTO','Publicidad',null,null,false,4,true),
('CATEGORIA_GASTO','Empaque',null,null,false,5,true),
('CATEGORIA_GASTO','Envíos',null,null,false,6,true),
('CATEGORIA_GASTO','Comisiones',null,null,false,7,true),
('CATEGORIA_GASTO','Operación',null,null,false,8,true),
('CATEGORIA_GASTO','Otros',null,null,false,9,true),
('COMPONENTE_COSTO','Tela',null,null,false,1,true),
('COMPONENTE_COSTO','Confección',null,null,false,2,true),
('COMPONENTE_COSTO','Estampado',null,null,false,3,true),
('COMPONENTE_COSTO','Bordado',null,null,false,4,true),
('COMPONENTE_COSTO','Etiquetas',null,null,false,5,true),
('COMPONENTE_COSTO','Empaque',null,null,false,6,true),
('COMPONENTE_COSTO','Transporte',null,null,false,7,true),
('COMPONENTE_COSTO','Otros',null,null,false,8,true),
('ESTADO','Pedido recibido','#D2DE52','PEDIDO',false,1,true),
('ESTADO','Pago pendiente','#F4B740','PEDIDO',false,2,true),
('ESTADO','Pagado','#5BC48B','PEDIDO',false,3,true),
('ESTADO','En preparación','#7FB2F0','PEDIDO',false,4,true),
('ESTADO','En producción','#9B7FF0','PEDIDO',false,5,true),
('ESTADO','Listo','#5BC48B','PEDIDO',false,6,true),
('ESTADO','Enviado','#E8288E','PEDIDO',false,7,true),
('ESTADO','Entregado','#3AA76D','PEDIDO',true,8,true),
('ESTADO','Cancelado','#C4C4C4','PEDIDO',true,9,true),
('ESTADO','Activo','#D2DE52','APARTADO',false,10,true),
('ESTADO','Abono pendiente','#F4B740','APARTADO',false,11,true),
('ESTADO','Pagado','#5BC48B','APARTADO',false,12,true),
('ESTADO','Entregado','#3AA76D','APARTADO',true,13,true),
('ESTADO','Cancelado','#C4C4C4','APARTADO',true,14,true),
('ESTADO','Vencido','#D33A2C','APARTADO',true,15,true),
('ESTADO','Pendiente','#F4B740','PAGO',false,16,true),
('ESTADO','Abono','#7FB2F0','PAGO',false,17,true),
('ESTADO','Pagado','#3AA76D','PAGO',true,18,true),
('ESTADO','Reembolsado','#C4C4C4','PAGO',true,19,true)
on conflict (tipo, nombre, ambito) do nothing;
